# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Repos/ImageProcessorCore/sim/Nexys4/Nexys4.cache/wt [current_project]
set_property parent.project_path D:/Repos/ImageProcessorCore/sim/Nexys4/Nexys4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  D:/Repos/ImageProcessorCore/src/Packages.sv
  D:/Repos/ImageProcessorCore/src/CellProcessor_int.sv
  D:/Repos/ImageProcessorCore/src/CellProcessor.sv
  D:/Repos/ImageProcessorCore/src/CellIndicator.sv
  D:/Repos/ImageProcessorCore/src/ImageProcessorCore.sv
}
read_verilog -library xil_defaultlib {
  D:/Repos/ImageProcessorCore/src/SwitchDebouncer.v
  D:/Repos/ImageProcessorCore/src/sevensegment.v
}
read_xdc D:/Repos/ImageProcessorCore/src/nexys4fpga.xdc
set_property used_in_implementation false [get_files D:/Repos/ImageProcessorCore/src/nexys4fpga.xdc]

synth_design -top Nexys4fpga -part xc7a100tcsg324-3
write_checkpoint -noxdef Nexys4fpga.dcp
catch { report_utilization -file Nexys4fpga_utilization_synth.rpt -pb Nexys4fpga_utilization_synth.pb }
